### PR TITLE
Add support for raw ecdsa without hashing

### PR DESCRIPTION
**Pull request by swissbit-csteuer**
Allows
```
Signature.getInstance(MessageDigest.ALG_NULL, Signature.SIG_CIPHER_ECDSA, Cipher.PAD_NULL, false);
```
Related to https://github.com/OpenSC/OpenSC/pull/2642 and https://github.com/philipWendland/IsoApplet/pull/28

### CODE REVIEW

**Comment by swissbit-csteuer** [comment]
Hi @Jakuje, could you take a look at this. The change is required for testing the coming isoapplet v1 version in the OpenSC CI build.

**Comment by Jakuje** [comment]
I am sorry for a delay, I am not getting notifications for new issues or pull request from github. First of all, this is just a fork used exclusively for the OpenSC CI so I would like you to ask to fill the PR also to the original repository https://github.com/licel/jcardsim ... it looks inactive as my PR hangs there for over a year, but from time to time something gets merged ...

Please, squash the commits too so we do not have the bogus fixup commit in there.

I am not familiar with the code, but it looks ok from the fast review.

**Comment by swissbit-csteuer** [comment]
Thanks for the review.

I squashed the commits and created a PR in the original repo: https://github.com/licel/jcardsim/pull/201

**Review by Jakuje — APPROVED** [review]

**Comment by Jakuje** [comment]
Thanks. I will keep an eye on this. I did not manage to go through the changes in the OpenSC yet. I assume they would be blocked by this so I am going to merge this and lets see what is going to happen in the CI.

Thank you for the contribution!

**Pull request merged**
